const models = {
    list: [
        {src: 'English', target: 'Arabic', model: 'en-ar'},
        {src: 'English', target: 'Bulgarian', model: 'en-bg'},
        {src: 'English', target: 'Czech', model: 'en-cs'},
        {src: 'English', target: 'Danish', model: 'en-da'},
        {src: 'English', target: 'German', model: 'en-de'},
        {src: 'English', target: 'Greek', model: 'en-el'},
        {src: 'English', target: 'Spanish', model: 'en-es'},
        {src: 'English', target: 'Estonian', model: 'en-et'},
        {src: 'English', target: 'Finnish', model: 'en-fi'},
        {src: 'English', target: 'French', model: 'en-fr'},
        {src: 'English', target: 'Hebrew', model: 'en-he'},
        {src: 'English', target: 'Hindi', model: 'en-hi'},
        {src: 'English', target: 'Croatian', model: 'en-hr'},
        {src: 'English', target: 'Italian', model: 'en-it'},
        {src: 'English', target: 'Japanese', model: 'en-ja'},
        {src: 'English', target: 'Korean', model: 'en-ko'},
        {src: 'English', target: 'Norwegian Bokmal', model: 'en-nb'},
        {src: 'English', target: 'Dutch', model: 'en-nl'},
        {src: 'English', target: 'Polish', model: 'en-pl'},
        {src: 'English', target: 'Portuguese', model: 'en-pt'},
        {src: 'English', target: 'Romanian', model: 'en-ro'},
        {src: 'English', target: 'Russian', model: 'en-ru'},
        {src: 'English', target: 'Slovak', model: 'en-sk'},
        {src: 'English', target: 'Slovenian', model: 'en-sl'},
        {src: 'English', target: 'Swedish', model: 'en-sv'},
        {src: 'English', target: 'Turkish', model: 'en-tr'},
        {src: 'English', target: 'Simplified Chinese', model: 'en-zh'},
        {src: 'English', target: 'Traditional Chinese', model: 'en-zh-TW'},
        {src: 'Arabic', target: 'English', model: 'ar-en'},
        {src: 'Bulgarian', target: 'English', model: 'bg-en'},
        {src: 'Catalan', target: 'Spanish', model: 'ca-es'},
        {src: 'Simplified Chinese', target: 'English', model: 'zh-en'},
        {src: 'Traditional Chinese', target: 'English', model: 'zh-TW-en'},
        {src: 'Croatian', target: 'English', model: 'hr-en'},
        {src: 'Czech', target: 'English', model: 'cs-en'},
        {src: 'Danish', target: 'English', model: 'da-en'},
        {src: 'Dutch', target: 'English', model: 'nl-en'},
        {src: 'Estonian', target: 'English', model: 'et-en'},
        {src: 'Finnish', target: 'English', model: 'fi-en'},
        {src: 'French', target: 'German', model: 'fr-de'},
        {src: 'French', target: 'English', model: 'fr-en'},
        {src: 'French', target: 'Spanish', model: 'fr-es'},
        {src: 'German', target: 'English', model: 'de-en'},
        {src: 'German', target: 'French', model: 'de-fr'},
        {src: 'German', target: 'Italian', model: 'de-it'},
        {src: 'Greek', target: 'English', model: 'el-en'},
        {src: 'Hebrew', target: 'English', model: 'he-en'},
        {src: 'Hindi', target: 'English', model: 'hi-en'},
        {src: 'Hungarian', target: 'English', model: 'hu-en'},
        {src: 'Italian', target: 'German', model: 'it-de'},
        {src: 'Italian', target: 'English', model: 'it-en'},
        {src: 'Japanese', target: 'English', model: 'ja-en'},
        {src: 'Korean', target: 'English', model: 'ko-en'},
        {src: 'Norwegian Bokmal', target: 'English', model: 'nb-en'},
        {src: 'Polish', target: 'English', model: 'pl-en'},
        {src: 'Portuguese', target: 'English', model: 'pt-en'},
        {src: 'Romanian', target: 'English', model: 'ro-en'},
        {src: 'Russian', target: 'English', model: 'ru-en'},
        {src: 'Slovak', target: 'English', model: 'sk-en'},
        {src: 'Slovenian', target: 'English', model: 'sl-en'},
        {src: 'Spanish', target: 'Catalan', model: 'es-ca'},
        {src: 'Spanish', target: 'English', model: 'es-en'},
        {src: 'Spanish', target: 'French', model: 'es-fr'},
        {src: 'Swedish', target: 'English', model: 'sv-en'},
        {src: 'Turkish', target: 'English', model: 'tr-en'},
    ]
}

export default models;